package com.example.karosuo.carcontrol;

import android.net.Uri;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by karosuo on 28/07/16.
 */
public class Trip {
    private int id;
    private String name;
    private Uri imgUri;
    private String fecha;
    private String trayectoria;
    private int duracion;


    public Trip(){
        /** Initialize in a null state.
         * This is used when want to init externally each member and reduce the amount of
         * parameters and increase readability*/
        this.setName(null);
        this.setImgUri(null);
        this.setTrayectoria(null);
        this.setDuracion(0);
        setId(0);
    }

    public Trip(String name, String imgUri, String trayectoria, int duracion){
        this.setName(name);
        this.setImgUri(imgUri);
        this.setTrayectoria(trayectoria);
        this.setDuracion(duracion);
        setId(0);
        /** ID of Trip is generated by the DB, but it exists on the object in order
         * to be able to set it when reads a trip from DB and wants to keep it's ID.
         * Mostly used when you make a search and wants to delete one of the occurences*/
    }

    public void setId(int newID){
        this.id = newID;
    }

    public int getId(){
        return this.id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImgUri() {
        return imgUri.toString();
    }

    public void setImgUri(String imgUri) {
        if (imgUri == null){
            this.imgUri = Uri.parse("android.resource://com.example.karosuo.carcontrol/drawable/default_map.png");
        }else {
            this.imgUri = Uri.parse(imgUri);
        }
    }

    public String getFecha() {
        /** Acording to ISO 8661 Date is in the format:
         * yyyy-MM-DD HH:mm */
        //It's autogenerated when it's about to be putted on the database
        return new SimpleDateFormat("yyyy-MM-DD HH:mm").format(new Date());
    }

    public void setFecha(String newFecha) {
        this.fecha = newFecha;
    }

    public String getTrayectoria() {
        return trayectoria;
    }

    public void setTrayectoria(String trayectoria) {
        this.trayectoria = trayectoria;
    }

    public int getDuracion() {
        return duracion;
    }

    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }

    public String toString(){
        return getName();
    }
}
